# Generated by Django 6.0.5 on 2026-05-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('link', models.URLField(help_text='Link to LeetCode or question bank')),
                ('question_count', models.CharField(default='0+ Questions', max_length=50)),
                ('needs_white_bg', models.BooleanField(default=True, help_text='Check if logo needs a white background wrapper')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
