# Generated by Django 6.0.5 on 2026-05-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyq_link', models.URLField(default='https://drive.google.com/drive/folders/1VT_6K9Q1zfIdbDLjf96YrsyEk3hfbMvX?usp=sharing', help_text='The URL for the IEM Previous Year Questions')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
