# Generated by Django 6.0.5 on 2026-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Alternatively, enter a direct image URL (e.g. from Imgur)', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
