# Generated by Django 6.0.5 on 2026-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_logo_url_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='pyq_link',
            field=models.URLField(blank=True, default='', help_text="The URL for the IEM Previous Year Questions. Leave blank to show 'Coming Soon' popup."),
        ),
    ]
