# Generated by Django 6.0.5 on 2026-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesetting_pyq_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain name for Logo.dev integration (e.g. accenture.com)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='repo_folder',
            field=models.CharField(blank=True, help_text='Folder name of this company in the local com/ directory (e.g. accenture)', max_length=100, null=True),
        ),
    ]
